version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=thuhocphi
      - MYSQL_ROOT_PASSWORD=878264
    ports:
      - '3307:3306'
    expose:
      - 3306
    networks:
      - network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: spring_app
    environment:
      - DB_PORT=3306
      - DB_HOST=db
    ports:
      - '8080:8080'
    networks:
      - network

networks:
  network:
    driver: bridge



